---
- name: Add a datacenter through REST
  vmware.vmware_rest.vcenter_datacenter:
    name: "{{ vsphere.datacenter }}"
  environment: "{{ vsphere_env }}"

- name: Add a datacenter
  community.vmware.vmware_datacenter:
    datacenter_name: "{{ vsphere.datacenter }}"
    state: present
  environment: "{{ vsphere_env }}"

- name: Add an cluster to the datacenter
  community.vmware.vmware_cluster:
    datacenter_name: "{{ vsphere.datacenter }}"
    cluster_name: "{{ vsphere.cluster }}"
    #Deprecate when this module stops touching DRS.
    #This module deprecated DRS management, but still changes it.
    #We control DRS in next task per guidance from nag warning.
    #Unfortunately, this module also controls DRS, just without
    #documentating it; ignore_drs tells it to surrender control      
    #Without this, both of these tasks will always say changed
    #ignore_drs: true 
  environment: "{{ vsphere_env }}"

- name: Add an cluster to the datacenter
  community.vmware.vmware_cluster:
    datacenter_name: "{{ vsphere.datacenter }}"
    cluster_name: "{{ vsphere.cluster }}"
  environment: "{{ vsphere_env }}"

- name: Enable DRS on the cluster to make scheduling easier
  community.vmware.vmware_cluster_drs:
    datacenter_name: "{{ vsphere.datacenter }}"
    cluster_name: "{{ vsphere.cluster }}"
    enable:  true
  environment: "{{ vsphere_env }}"
