dirs:
  config: "{{ ansible_env.HOME }}/build_config"
  artifact: "{{ ansible_env.HOME }}/build_artifact"
  explode: "{{ ansible_env.HOME }}/build_explode"
domain: dragonslair.dev
esxi_user:
  username: root
  password: BadPassword1234$ 
vsphere_user:
  username: "administrator@vsphere.{{ domain }}"
  password: BadPassword1234$
  root_password: BadPassword1234$
esxi:
  hostname: "esxi01.{{ domain }}"
  datastore: datastore1
vcsa_system_name: "vsphere.{{ domain }}"
vcsa_ip_address:  "{{ lookup('dig', vcsa_system_name ) }}"
vcsa_ip_prefix: 29
vcsa_ip_gateway:  "{{ lookup('dig', 'gateway.' + domain ) }}"
vcsa_dns_servers: 1.1.1.1
vcsa_sso_domain_name: "{{ vcsa_system_name }}"
vcsa_bucket: vcsatar
vcsa_tar_name: vcsa70.tar.gz
vcsa_config_file_name: "{{ vcsa_system_name }}.json"
