---
- name: Build config directories
  file:
    path: "{{ item }}"
    state: directory
  loop: 
   - "{{ dirs.config }}"
   - "{{ dirs.artifact }}"
   - "{{ dirs.explode }}"

- name: Template file out
  template:
    src: "embedded_vCSA_on_ESXi.json.j2"
    dest: "{{ dirs.config }}/{{ vcsa_config_file_name }}"

- name: Fetch archive of VCSA
  amazon.aws.aws_s3:
    bucket: "{{ vcsa_bucket }}"
    object: "{{ vcsa_tar_name }}"
    dest: "{{ dirs.artifact }}/{{ vcsa_tar_name }}"
    mode: get
    overwrite: different

- name: Untar archive 
  ansible.builtin.unarchive:
    src: "{{ dirs.artifact }}/vcsa70.tar.gz"
    dest: "{{ dirs.explode }}"

- name: Install libsnl to use OVFTool on Enterprise Linux
  yum:
    name: libnsl
    state: latest
  become: true

- name: Install VCSA
  command: "{{ dirs.explode }}/vcsa-cli-installer/lin64/vcsa-deploy install --accept-eula {{ dirs.config }}/{{ vcsa_config_file_name }}"

- ansible.builtin.pause:
    minutes: 5

- name: Add a datacenter
  vmware.vmware_rest.vcenter_datacenter:
    vcenter_hostname: "{{ vcsa_system_name }}"
    vcenter_username: "{{ vsphere_user.username }}" 
    vcenter_password: "{{ vsphere_user.password }}" 
    vcenter_validate_certs: no
    folder: Datacenters
    name: Datacenter
    state: present

- name: Add an ESXi host
  vmware.vmware_rest.vcenter_host:
    vcenter_hostname: "{{ vcsa_system_name }}"
    vcenter_username: "{{ vsphere_user.username }}"
    vcenter_password: "{{ vsphere_user.password }}" 
    vcenter_validate_certs: no
    thumbprint_verification: NONE
    hostname: "{{ esxi.hostname }}"
    user_name: "{{ esxi_user.username }}"
    password: "{{ esxi_user.password }}"
    state: present
