---
- name: Build config directories
  file:
    path: "{{ item }}"
    state: directory
  loop: 
   - "{{ dirs.config }}"
   - "{{ dirs.artifact }}"
   - "{{ dirs.explode }}"

- name: Template file out
  template:
    src: "embedded_vCSA_on_ESXi.json.j2"
    dest: "{{ dirs.config }}/{{ vcsa_config_file_name }}"

- name: Fetch archive of VCSA
  amazon.aws.aws_s3:
    bucket: "{{ vcsa_bucket }}"
    object: "{{ vcsa_tar_name }}"
    dest: "{{ dirs.artifact }}/{{ vcsa_tar_name }}"
    mode: get
    overwrite: different

- name: Untar archive 
  ansible.builtin.unarchive:
    src: "{{ dirs.artifact }}/vcsa70.tar.gz"
    dest: "{{ dirs.explode }}"

#You must have libnsl installed (RHEL: yum install libnsl); not all systems default to this.  The execution environment has it
- name: Install VCSA
  command: "{{ dirs.explode }}/vcsa-cli-installer/lin64/vcsa-deploy install --accept-eula {{ dirs.config }}/{{ vcsa_config_file_name }}"

- name: Create Datacenter
  community.vmware.vmware_datacenter:
    hostname: "{{ vcsa_system_name }}"
    username: "{{ vsphere_user.username }}" 
    password: "{{ vsphere_user.password }}" 
    datacenter_name: Datacenter
    state: present
    validate_certs: no
  register: datacenter_creation
  until: datacenter_creation is not failed 
  retries: 60
  delay: 10

- name: Remove Datacenter
  community.vmware.vmware_datacenter:
    hostname: "{{ vcsa_system_name }}"
    username: "{{ vsphere_user.username }}" 
    password: "{{ vsphere_user.password }}" 
    datacenter_name: Datacenter
    state: absent
    validate_certs: no
