#To create the templates
#ansible-playbook -i ~/disconnectedinfra/inventory.yml template.yml
#To cleanup the generated templates and terraform state
#ansible-playbook -i ~/disconnectedinfra/inventory.yml template.yml -t never
---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    files: "{{ lookup('ansible.builtin.fileglob', '*.j2', wantlist=True) | map('splitext') | map('first') }}"
    terraform_files:
    - .terraform
    - .terraform.lock.hcl
    - tfplan

  tasks:
  - template:
      src: "{{ item }}.j2"
      dest: "{{ item }}"
    loop: "{{ files }}"

  - file:
      name: "{{ item }}"
      state: absent
    loop: "{{ files + terraform_files }}"
    tags:
    - never
